/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    neighbourhoods: Neighbourhood;
    'news-categories': NewsCategory;
    'event-categories': EventCategory;
    'business-categories': BusinessCategory;
    businesses: Business;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    neighbourhoods: NeighbourhoodsSelect<false> | NeighbourhoodsSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    'event-categories': EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    'business-categories': BusinessCategoriesSelect<false> | BusinessCategoriesSelect<true>;
    businesses: BusinessesSelect<false> | BusinessesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      heartbeat: TaskHeartbeat;
      'seed-directory': TaskSeedDirectory;
      'check-staleness': TaskCheckStaleness;
      'dedup-flag': TaskDedupFlag;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * admin/operator staff the CMS; business-owner manages claimed listings only.
   */
  roles: ('admin' | 'operator' | 'business-owner')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city?: (string | null) | City;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  name: string;
  /**
   * URL-safe identifier, e.g. "kingston".
   */
  slug: string;
  /**
   * Hostnames that resolve to this city (e.g. kingston.fyi, www.kingston.fyi, localhost). Case-insensitive, port-stripped.
   */
  hostnames: {
    hostname: string;
    id?: string | null;
  }[];
  /**
   * IANA timezone, e.g. America/Toronto.
   */
  timezone: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighbourhoods".
 */
export interface Neighbourhood {
  id: string;
  name: string;
  /**
   * Leave blank to derive from name.
   */
  slug?: string | null;
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: string;
  name: string;
  /**
   * Leave blank to derive from name.
   */
  slug?: string | null;
  /**
   * Editorial tag colour (hex), e.g. #2f6d6a.
   */
  color: string;
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories".
 */
export interface EventCategory {
  id: string;
  name: string;
  /**
   * Leave blank to derive from name.
   */
  slug?: string | null;
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories".
 */
export interface BusinessCategory {
  id: string;
  name: string;
  /**
   * Leave blank to derive from name.
   */
  slug?: string | null;
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  parent?: (string | null) | BusinessCategory;
  breadcrumbs?:
    | {
        doc?: (string | null) | BusinessCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses".
 */
export interface Business {
  id: string;
  name: string;
  /**
   * Leave blank to derive from name.
   */
  slug?: string | null;
  /**
   * Short one-line summary shown on cards and in search results.
   */
  blurb?: string | null;
  /**
   * Longer "About" content for the detail page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The most-specific (leaf) category. The parent is derived from the category hierarchy.
   */
  category?: (string | null) | BusinessCategory;
  neighbourhood?: (string | null) | Neighbourhood;
  /**
   * Relative price level.
   */
  priceTier?: ('$' | '$$' | '$$$' | '$$$$') | null;
  /**
   * Structured opening intervals (one row per open period). A day with no row is treated as closed. Open-Now is derived from these in America/Toronto.
   */
  hours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * 24h HH:MM
         */
        opens: string;
        /**
         * 24h HH:MM
         */
        closes: string;
        id?: string | null;
      }[]
    | null;
  address?: {
    street?: string | null;
    locality?: string | null;
    region?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  /**
   * Full URL including https://
   */
  website?: string | null;
  /**
   * Amenity tags (e.g. "patio", "wheelchair accessible", "wifi").
   */
  amenities?: string[] | null;
  /**
   * Photo gallery (first image is the lead). Stored via the media adapter.
   */
  photos?: (string | Media)[] | null;
  /**
   * Sourced display rating (0–5). Never emitted as structured aggregateRating.
   */
  rating?: number | null;
  /**
   * Sourced review count (display only).
   */
  reviewCount?: number | null;
  /**
   * Coordinates as [longitude, latitude] (SRID 4326). Stored as a PostGIS geometry(Point,4326); a GiST index powers radius / map-bounds queries.
   *
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  /**
   * Operational lifecycle state (FR58).
   */
  lifecycleStatus?: ('active' | 'temporarily-closed' | 'permanently-closed' | 'stale-unverified') | null;
  /**
   * Google Place ID (re-seed / refresh key).
   */
  placeId?: string | null;
  /**
   * Operator review flags.
   */
  directoryFlags?: {
    flaggedDuplicate?: boolean | null;
    /**
     * Likely-duplicate listing flagged for operator merge.
     */
    duplicateCandidate?: (string | null) | Business;
  };
  /**
   * Data provenance (FR56). Controls what re-seeding may overwrite.
   */
  provenance: {
    /**
     * Origin of this record’s data.
     */
    source: 'seeded' | 'google-places' | 'owner-edited' | 'operator';
    /**
     * Field paths owned by the owner. Re-seeding never overwrites these.
     */
    lockedFields?: string[] | null;
    /**
     * True for ToS-bound sources (e.g. Google Places) re-fetched on cadence.
     */
    refreshRequired?: boolean | null;
    /**
     * When source data was last refreshed.
     */
    lastRefreshedAt?: string | null;
  };
  /**
   * Moderation state. Public pages show approved/published only.
   */
  status: 'draft' | 'pending' | 'approved' | 'published';
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  /**
   * Reviewer display name from the source.
   */
  author?: string | null;
  /**
   * Star rating, 1–5.
   */
  rating: number;
  reviewDate?: string | null;
  text?: string | null;
  business: string | Business;
  /**
   * Data provenance (FR56). Controls what re-seeding may overwrite.
   */
  provenance: {
    /**
     * Origin of this record’s data.
     */
    source: 'seeded' | 'google-places' | 'owner-edited' | 'operator';
    /**
     * Field paths owned by the owner. Re-seeding never overwrites these.
     */
    lockedFields?: string[] | null;
    /**
     * True for ToS-bound sources (e.g. Google Places) re-fetched on cadence.
     */
    refreshRequired?: boolean | null;
    /**
     * When source data was last refreshed.
     */
    lastRefreshedAt?: string | null;
  };
  /**
   * Moderation state. Public pages show approved/published only.
   */
  status: 'draft' | 'pending' | 'approved' | 'published';
  /**
   * The city this record belongs to. Enforced by cityScoped() access.
   */
  city: string | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'heartbeat' | 'seed-directory' | 'check-staleness' | 'dedup-flag';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'heartbeat' | 'seed-directory' | 'check-staleness' | 'dedup-flag') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'neighbourhoods';
        value: string | Neighbourhood;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: string | NewsCategory;
      } | null)
    | ({
        relationTo: 'event-categories';
        value: string | EventCategory;
      } | null)
    | ({
        relationTo: 'business-categories';
        value: string | BusinessCategory;
      } | null)
    | ({
        relationTo: 'businesses';
        value: string | Business;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  hostnames?:
    | T
    | {
        hostname?: T;
        id?: T;
      };
  timezone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "neighbourhoods_select".
 */
export interface NeighbourhoodsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-categories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-categories_select".
 */
export interface BusinessCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businesses_select".
 */
export interface BusinessesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  blurb?: T;
  description?: T;
  category?: T;
  neighbourhood?: T;
  priceTier?: T;
  hours?:
    | T
    | {
        day?: T;
        opens?: T;
        closes?: T;
        id?: T;
      };
  address?:
    | T
    | {
        street?: T;
        locality?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  phone?: T;
  website?: T;
  amenities?: T;
  photos?: T;
  rating?: T;
  reviewCount?: T;
  location?: T;
  lifecycleStatus?: T;
  placeId?: T;
  directoryFlags?:
    | T
    | {
        flaggedDuplicate?: T;
        duplicateCandidate?: T;
      };
  provenance?:
    | T
    | {
        source?: T;
        lockedFields?: T;
        refreshRequired?: T;
        lastRefreshedAt?: T;
      };
  status?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  reviewDate?: T;
  text?: T;
  business?: T;
  provenance?:
    | T
    | {
        source?: T;
        lockedFields?: T;
        refreshRequired?: T;
        lastRefreshedAt?: T;
      };
  status?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskHeartbeat".
 */
export interface TaskHeartbeat {
  input?: unknown;
  output: {
    ranAt?: string | null;
    ingestStatus?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSeed-directory".
 */
export interface TaskSeedDirectory {
  input: {
    maxPerQuery?: number | null;
  };
  output: {
    discovered?: number | null;
    created?: number | null;
    updated?: number | null;
    skipped?: number | null;
    configured?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCheck-staleness".
 */
export interface TaskCheckStaleness {
  input?: unknown;
  output: {
    flagged?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDedup-flag".
 */
export interface TaskDedupFlag {
  input?: unknown;
  output: {
    scanned?: number | null;
    flagged?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}